### ISSUE TITLE
Translating to codeclimate breaks after SimpleCov update

### ISSUE THREAD

**Issue by bradleybeddoes** [travelaudience/orbs#123]
### Orb Name

code-climate

### Orb version

0.1.5

### Actual Behaviour

Does not translate to code-climate coverage format with latest simplecov JSON output

### Expected Behaviour

Translates to code-climate coverage format with latest simplecov JSON output

### Steps to Reproduce

```
- code-climate/format_coverage:
                input_type: simplecov
                coverage_file: .../simplecov/coverage.json
                output: .../simplecov.json
```

Appears to be solved already by https://github.com/codeclimate-community/simplecov_json_formatter/issues/4 likely just needs a version bump of `cc-test-reporter`.
